[project]
name = "trivy-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Juan Alvarez", email = "j.alvarezg@eurodivisas.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.4",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]

