replicaCount: 1

image:
  repository: trivy-project
  tag: local
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 10001