apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jualvarez9/trivy-project.git
    targetRevision: master
    path: helm/trivy-project
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true