replicaCount: 1

image:
  repository: ghcr.io/jualvarez9/trivy-project-frontend
  tag: latest
  pullPolicy: Always

backendService: todo-backend

service:
  type: ClusterIP
  port: 8080

securityContext:
  runAsNonRoot: true
  runAsUser: 101
  runAsGroup: 101
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

podSecurityContext:
  fsGroup: 101